#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
import os

# Import from amazing
from amazing.lib import try_me

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'amazing_description'
    try_me()
